import { Button, VerticalBox, HorizontalBox, ScrollView} from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 400px;
    min-height: 200px;
    preferred-width: 1100px;
    preferred-height: 600px;
    title: "File Manager";
//    in-out property <int> counter: 42;
//    callback request-increase-value();
//    VerticalBox {
//        Text {
//            text: "Counter: \{root.counter}";
//        }
//
//        Button {
//            text: "Increase value";
//            clicked => {
//                root.request-increase-value();
//            }
//        }
//    }

    in property <[string]> files;
    in-out property <string> directory : "/home/brindy/";
    callback change-current-directory();
    HorizontalBox {
        padding: 0;
        spacing: 0;

        // Side panel
        Rectangle {
            background: black;
            width: 15%;
        }

        VerticalBox {
            padding: 0;
            spacing: 0;

            // Top panel
            Rectangle {
                background: blue;
                height: 15%;
                TextInput {
                    text <=> root.directory;
                    font-size: 18px;
                    key-pressed(event) => {
                        if(event.text == Key.Return) {
                            root.change-current-directory();
                            return EventResult.accept;
                        }
                        return EventResult.reject;
                    }
                }
            }

//            // Content
//            Rectangle {
//                background: white;
//            }
            // TODO: Make VerticalBox scrollable, maybe ScrollView ?
//            VerticalBox {
//                alignment: start;
//
//                for file in files: Text {
//                    text: file;
//                    font-size: 18px;
//                }
//            }
            ScrollView {
                // TODO: Make a grid instead of VerticalBox
                VerticalBox {
                spacing: 10px;
                    for file in files: Rectangle {
                        background: white;
                        height: 40px;
                        border-radius: 15px;
                        Text {
                            text: file;
                            color: black;
                            font-size: 18px;
                        }

                    }
                }
            }
        }
    }
}