import { Button, VerticalBox, HorizontalBox, ScrollView, StandardButton} from "std-widgets.slint";

export enum FileItemType {
    FILE,
    DIRECTORY
}

export struct FileItem {
    name: string,
    size: float,
    fileType: FileItemType
}

export component ErrorDialog inherits Dialog {
    title: "Error in the provided path";
    preferred-width: 110px;
    preferred-height: 60px;
    in-out property <string> error_text;
    callback close-dialog();
    
    Text {
        text: error_text;
    }
    StandardButton {
        kind: ok;
        clicked => {
            root.close-dialog();
        }}
}

export component AppWindow inherits Window {
    min-width: 400px;
    min-height: 200px;
    preferred-width: 1100px;
    preferred-height: 600px;
    title: "File Manager";
//    in-out property <int> counter: 42;
//    callback request-increase-value();
//    VerticalBox {
//        Text {
//            text: "Counter: \{root.counter}";
//        }
//
//        Button {
//            text: "Increase value";
//            clicked => {
//                root.request-increase-value();
//            }
//        }
//    }

    in property <[FileItem]> files;
    in-out property <string> directory : "/home/brindy/";
    callback change-current-directory();
    HorizontalBox {
        padding: 0;
        spacing: 0;

        // Side panel
        Rectangle {
            background: black;
            width: 15%;
        }

        VerticalBox {
            padding: 0;
            spacing: 0;

            // Top panel
            Rectangle {
                background: blue;
                height: 15%;
                TextInput {
                    text <=> root.directory;
                    font-size: 18px;
                    key-pressed(event) => {
                        if(event.text == Key.Return) {
                            root.change-current-directory();
                            return EventResult.accept;
                        }
                        return EventResult.reject;
                    }
                }
            }

            // Files
            ScrollView {
                vertical-scrollbar-policy: always-on;
                horizontal-scrollbar-policy: always-off;

                GridLayout {
                    spacing-horizontal: 50px;
                    spacing-vertical: 25px;

                    for file[i] in files: Rectangle {
                        row: i / 6;
                        border-radius: 15px;
                        background: white;
                        height: 100px;
                        width: 100px;

                        Text {
                            text: file.name;
                            color: black;
                            font-size: 18px;
                        }
                    }
                }
            }
        }
    }
}